const initialState = {
  app: {
    data: [{
      id: 1,
      first_name: "Dmytro",
      last_name: "Hlushchuk",
      password: "any_pass",
      email: "shaolanych@gmail.com",
      phone: "+380672560439",
      country: "Ukraine",
      b_day: "1994-06-02",
    },
    {
      id: 2,
      first_name: "Viktor",
      last_name: "Skydanchuk",
      password: "any_pass1",
      email: "skydanchuk@gmail.com",
      phone: "+380974713925",
      country: "Ukraine",
      b_day: "1994-10-03",
    },
    {
      id: 3,
      first_name: "Oleksandr",
      last_name: "Lysenko",
      password: "keywork",
      email: "s.lysenko@gmail.com",
      phone: "+380967469815",
      country: "Ukraine",
      b_day: "1994-09-26",
    },
    {
      id: 4,
      first_name: "Vitalii",
      last_name: "Ilchenko",
      password: "seo_pass",
      email: "ilchenko@gmail.com",
      phone: "+380666885327",
      country: "Ukraine",
      b_day: "1998-07-12",
    },
    {
      id: 5,
      first_name: "Vlad",
      last_name: "Viunov",
      password: "fsdfs",
      email: "v.viunov@gmail.com",
      phone: "+380952580739",
      country: "Ukraine",
      b_day: "1998-02-25",
    },
    {
      id: 6,
      first_name: "Dmytro",
      last_name: "Maltsev",
      password: "ruby_coder1",
      email: "tankist@gmail.com",
      phone: "+380668853719",
      country: "Ukraine",
      b_day: "1993-04-17",
    },
    {
      id: 7,
      first_name: "Evgenii",
      last_name: "Tymofii",
      password: "ffhhh3hhf",
      email: "grey.warrior@gmail.com",
      phone: "+380672560719",
      country: "Ukraine",
      b_day: "1992-02-15",
    }],
    columns: [{ name: 'id', alias: 'ID' }, { name: 'first_name', alias: 'First name' }, { name: 'last_name', alias: 'Last Name' }, { name: 'password', alias: 'Password' }, { name: 'email', alias: 'Email' }, { name: 'phone', alias: 'Phone' }, { name: 'country', alias: 'Country' }, { name: 'b_day', alias: 'BDay' }],
    selected: [{ name: 'id', alias: 'ID' }, { name: 'first_name', alias: 'First name' }, { name: 'last_name', alias: 'Last Name' }],
  },
}

export default initialState;